version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: docqa-backend
    environment:
      - TONGYI_API_KEY=${TONGYI_API_KEY}
      - GIN_MODE=release
      - PORT=8080
      - STORAGE_PATH=/app/data/files
      - VECTORDB_PATH=/app/data/vectordb
      - DATA_DIR=/app/data            # 添加数据目录环境变量
      - LOG_LEVEL=info
      - LOG_OUTPUT=both
      - LOG_DIR=/app/logs
    volumes:
      - docqa-data:/app/data
      - docqa-logs:/app/logs          # 添加日志目录卷
    ports:
      - "8080:8080"
    restart: unless-stopped

  frontend:
    build:
      context: ./doc-vue
      dockerfile: Dockerfile
    container_name: docqa-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  docqa-data:
    driver: local
  docqa-logs:                         # 添加日志卷
    driver: local