version: '3.8'

services:
  # Redis for cache and task queue
  redis:
    image: redis:7-alpine
    container_name: docqa-test-redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 3

  # MinIO for object storage
  minio:
    image: minio/minio:latest
    container_name: docqa-test-minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 5s
      timeout: 5s
      retries: 3
    volumes:
      - minio_data:/data

  # Python Worker service
  py-worker:
    build:
      context: ../../py-services
      dockerfile: Dockerfile.worker
    container_name: docqa-test-py-worker
    depends_on:
      - redis
      - minio
    environment:
      - REDIS_URL=redis://redis:6379/0
      - DASHSCOPE_API_KEY=${DASHSCOPE_API_KEY}
      - MINIO_ENDPOINT=minio:9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
      - MINIO_BUCKET=docqa-test
      - LOG_LEVEL=DEBUG
      - CALLBACK_URL=http://localhost:8080/api/tasks/callback
    volumes:
      - ./.env:/app/.env
    restart: unless-stopped

  py-api:
    build:
      context: ../../py-services
      dockerfile: Dockerfile.api  # Create a separate Dockerfile for the API
    container_name: docqa-test-py-api
    depends_on:
      - redis
      - minio
      - py-worker
    ports:
      - "8000:8000"
    environment:
      - REDIS_URL=redis://redis:6379/0
      - DASHSCOPE_API_KEY=${DASHSCOPE_API_KEY}
      - MINIO_ENDPOINT=minio:9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
      - MINIO_BUCKET=docqa-test
      - LOG_LEVEL=DEBUG
    volumes:
      - ./.env:/app/.env
    restart: unless-stopped
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --log-level info

networks:
  default:
    name: docqa-test-network

volumes:
  minio_data:
    driver: local