// Code generated by mockery v2.50.0. DO NOT EDIT.

package taskqueue

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockQueue is an autogenerated mock type for the Queue type
type MockQueue struct {
	mock.Mock
}

type MockQueue_Expecter struct {
	mock *mock.Mock
}

func (_m *MockQueue) EXPECT() *MockQueue_Expecter {
	return &MockQueue_Expecter{mock: &_m.Mock}
}

// Close provides a mock function with no fields
func (_m *MockQueue) Close() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockQueue_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockQueue_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockQueue_Expecter) Close() *MockQueue_Close_Call {
	return &MockQueue_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockQueue_Close_Call) Run(run func()) *MockQueue_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockQueue_Close_Call) Return(_a0 error) *MockQueue_Close_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockQueue_Close_Call) RunAndReturn(run func() error) *MockQueue_Close_Call {
	_c.Call.Return(run)
	return _c
}

// Enqueue provides a mock function with given fields: task
func (_m *MockQueue) Enqueue(task *Task) (string, error) {
	ret := _m.Called(task)

	if len(ret) == 0 {
		panic("no return value specified for Enqueue")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(*Task) (string, error)); ok {
		return rf(task)
	}
	if rf, ok := ret.Get(0).(func(*Task) string); ok {
		r0 = rf(task)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(*Task) error); ok {
		r1 = rf(task)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockQueue_Enqueue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Enqueue'
type MockQueue_Enqueue_Call struct {
	*mock.Call
}

// Enqueue is a helper method to define mock.On call
//   - task *Task
func (_e *MockQueue_Expecter) Enqueue(task interface{}) *MockQueue_Enqueue_Call {
	return &MockQueue_Enqueue_Call{Call: _e.mock.On("Enqueue", task)}
}

func (_c *MockQueue_Enqueue_Call) Run(run func(task *Task)) *MockQueue_Enqueue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*Task))
	})
	return _c
}

func (_c *MockQueue_Enqueue_Call) Return(_a0 string, _a1 error) *MockQueue_Enqueue_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockQueue_Enqueue_Call) RunAndReturn(run func(*Task) (string, error)) *MockQueue_Enqueue_Call {
	_c.Call.Return(run)
	return _c
}

// GetTask provides a mock function with given fields: ctx, taskID
func (_m *MockQueue) GetTask(ctx context.Context, taskID string) (*Task, error) {
	ret := _m.Called(ctx, taskID)

	if len(ret) == 0 {
		panic("no return value specified for GetTask")
	}

	var r0 *Task
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*Task, error)); ok {
		return rf(ctx, taskID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *Task); ok {
		r0 = rf(ctx, taskID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Task)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, taskID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockQueue_GetTask_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTask'
type MockQueue_GetTask_Call struct {
	*mock.Call
}

// GetTask is a helper method to define mock.On call
//   - ctx context.Context
//   - taskID string
func (_e *MockQueue_Expecter) GetTask(ctx interface{}, taskID interface{}) *MockQueue_GetTask_Call {
	return &MockQueue_GetTask_Call{Call: _e.mock.On("GetTask", ctx, taskID)}
}

func (_c *MockQueue_GetTask_Call) Run(run func(ctx context.Context, taskID string)) *MockQueue_GetTask_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockQueue_GetTask_Call) Return(_a0 *Task, _a1 error) *MockQueue_GetTask_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockQueue_GetTask_Call) RunAndReturn(run func(context.Context, string) (*Task, error)) *MockQueue_GetTask_Call {
	_c.Call.Return(run)
	return _c
}

// MarkComplete provides a mock function with given fields: ctx, taskID, result
func (_m *MockQueue) MarkComplete(ctx context.Context, taskID string, result map[string]interface{}) error {
	ret := _m.Called(ctx, taskID, result)

	if len(ret) == 0 {
		panic("no return value specified for MarkComplete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, map[string]interface{}) error); ok {
		r0 = rf(ctx, taskID, result)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockQueue_MarkComplete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkComplete'
type MockQueue_MarkComplete_Call struct {
	*mock.Call
}

// MarkComplete is a helper method to define mock.On call
//   - ctx context.Context
//   - taskID string
//   - result map[string]interface{}
func (_e *MockQueue_Expecter) MarkComplete(ctx interface{}, taskID interface{}, result interface{}) *MockQueue_MarkComplete_Call {
	return &MockQueue_MarkComplete_Call{Call: _e.mock.On("MarkComplete", ctx, taskID, result)}
}

func (_c *MockQueue_MarkComplete_Call) Run(run func(ctx context.Context, taskID string, result map[string]interface{})) *MockQueue_MarkComplete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(map[string]interface{}))
	})
	return _c
}

func (_c *MockQueue_MarkComplete_Call) Return(_a0 error) *MockQueue_MarkComplete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockQueue_MarkComplete_Call) RunAndReturn(run func(context.Context, string, map[string]interface{}) error) *MockQueue_MarkComplete_Call {
	_c.Call.Return(run)
	return _c
}

// MarkFailed provides a mock function with given fields: ctx, taskID, errMsg
func (_m *MockQueue) MarkFailed(ctx context.Context, taskID string, errMsg string) error {
	ret := _m.Called(ctx, taskID, errMsg)

	if len(ret) == 0 {
		panic("no return value specified for MarkFailed")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, taskID, errMsg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockQueue_MarkFailed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkFailed'
type MockQueue_MarkFailed_Call struct {
	*mock.Call
}

// MarkFailed is a helper method to define mock.On call
//   - ctx context.Context
//   - taskID string
//   - errMsg string
func (_e *MockQueue_Expecter) MarkFailed(ctx interface{}, taskID interface{}, errMsg interface{}) *MockQueue_MarkFailed_Call {
	return &MockQueue_MarkFailed_Call{Call: _e.mock.On("MarkFailed", ctx, taskID, errMsg)}
}

func (_c *MockQueue_MarkFailed_Call) Run(run func(ctx context.Context, taskID string, errMsg string)) *MockQueue_MarkFailed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockQueue_MarkFailed_Call) Return(_a0 error) *MockQueue_MarkFailed_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockQueue_MarkFailed_Call) RunAndReturn(run func(context.Context, string, string) error) *MockQueue_MarkFailed_Call {
	_c.Call.Return(run)
	return _c
}

// MarkProcessing provides a mock function with given fields: ctx, taskID
func (_m *MockQueue) MarkProcessing(ctx context.Context, taskID string) error {
	ret := _m.Called(ctx, taskID)

	if len(ret) == 0 {
		panic("no return value specified for MarkProcessing")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, taskID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockQueue_MarkProcessing_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkProcessing'
type MockQueue_MarkProcessing_Call struct {
	*mock.Call
}

// MarkProcessing is a helper method to define mock.On call
//   - ctx context.Context
//   - taskID string
func (_e *MockQueue_Expecter) MarkProcessing(ctx interface{}, taskID interface{}) *MockQueue_MarkProcessing_Call {
	return &MockQueue_MarkProcessing_Call{Call: _e.mock.On("MarkProcessing", ctx, taskID)}
}

func (_c *MockQueue_MarkProcessing_Call) Run(run func(ctx context.Context, taskID string)) *MockQueue_MarkProcessing_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockQueue_MarkProcessing_Call) Return(_a0 error) *MockQueue_MarkProcessing_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockQueue_MarkProcessing_Call) RunAndReturn(run func(context.Context, string) error) *MockQueue_MarkProcessing_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockQueue creates a new instance of MockQueue. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockQueue(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockQueue {
	mock := &MockQueue{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
